name: SAM Application Workflow candidate "2029"

on: 
  push:
    branches:
      - main
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install dependencies and build SAM application
        run: |
          cd kjell/hello_world
          pip install -r requirements.txt
          pip install aws-sam-cli
          sam build --template-file ../template.yaml

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy SAM application
        run: |
          cd kjell/hello_world
          sam deploy --no-fail-on-empty-changeset --stack-name exampgr301-stack-candidate2029 --s3-bucket kjellsimagebucket --region ${{ secrets.AWS_REGION }} --capabilities CAPABILITY_IAM --template-file ../template.yaml
