name: SAM Application Workflow

on: 
  push:
    branches:
      - main
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies and build SAM application
        run: |
          cd kjell/hello_world
          pip install -r requirements.txt
          pip install aws-sam-cli
          sam build --template-file ../template.yaml

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy SAM application
        run: |
          cd kjell/hello_world
          sam deploy --guided --template-file ../template.yaml
