name: SAM Application Workflow

on: 
  push:
    branches:
      - main
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install dependencies and build SAM application
        run: |
          cd kjell/hello_world
          pip install -r requirements.txt
          pip install aws-sam-cli
          sam build --template-file ../template.yaml

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy SAM application
        run: |
          cd kjell/hello_world
          sam deploy --no-fail-on-empty-changeset --stack-name exampgr301stack --s3-bucket exampgr301bucket --region eu-west-1 --capabilities CAPABILITY_IAM
